#!/bin/bash

# TODO

# alias picom9600='picocom -b 9600  /dev/ttyUSB0 --echo --imap lfcrlf'
# alias picom4800='picocom -b 4800  /dev/ttyUSB0 --echo --imap lfcrlf'
# 
# arduinoFlash() {
#    avrdude -c stk500v1 -P /dev/ttyUSB0 -p atmega328p -b 19200 -U flash:w:$1:i
# }
