#!/bin/bash

# Limit number of processes ####################################################
#> if "OPERATING_SYSTEM" !~ "Cygwin"
ulimit -u 2000
#> endif

# Disable history expansion ####################################################
#  "set +o histexpand" does not work, we use +H instead
set +H

# Redraw within TMUX: ##########################################################
trap 'eval $(resize)' WINCH

# Disable ^S/^Q ################################################################
stty start '' stop ''

# vim: ft=sh
