#!/bin/bash

if tty | grep -qF 'tty'; then

   # () supresses [<JOB>] $PID ... [<JOB>]+ Done output
   (
      {
         if [ "$TERM" = "linux" ]; then
             #> include <vt_palette>
             clear #for background artifacting
         fi

         setfont Lat2-Terminus16.psfu.gz &>/dev/null
      } &
   )

fi

# vim: ft=sh
