#+defines
THEME_COLOR = blue
NICK = braph
JID = insert_jid_here
PASSWORD = insert_pw_here
PORT = 5222
#-defines

PP_MODULES = -m maths.pm

IGNORE_FILES = extractDefaultKeymap.sh mcabber/keymap mcabber/theme
INSTALL_DIRS = mcabber/history mcabber/otr

include ../makefiles/std.mk
