THEME_COLOR = blue
NICK = braph
JID = insert_jid_here
PASSWORD = insert_pw_here
PORT = 5222
HOST = auto

FILEPP_MODULES = maths.pm testfile.pm
IGNORE_FILES = extractDefaultKeymap.sh mcabber/keymap mcabber/theme
DIRECTORIES = mcabber/history mcabber/otr

include ../package.mk
