build:
	git clone https://github.com/caleb-/evilvte
	cp config.h evilvte/src/config.h
	sh -c 'cd evilvte && ./configure && make'

install:
	sh -c 'cd evilvte; sudo make install'

clean:
	rm -rf evilvte
	
