DEST = $(HOME)

# <parameters>
# </parameters>

# <filepp>
PP_KC = \#>

PP_MODULES =

PP_DEFINES =
# </filepp>

all:
#filepp -kc '$(PP_KC)' $(PP_MODULES) $(PP_DEFINES) zshrc -o .zshrc

install:
	mkdir -p $(DEST)/.config/tint2
	cp tint2rc $(DEST)/.config/tint2
